/**
 * Email Setup Script
 * Creates Ethereal test account automatically
 */

import nodemailer from "nodemailer";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function setupEtherealEmail() {
  console.log("🚀 Setting up Ethereal test email account...\n");

  try {
    // Create test account
    const testAccount = await nodemailer.createTestAccount();

    console.log("✅ Ethereal account created successfully!\n");
    console.log("📧 Email Credentials:");
    console.log("=".repeat(60));
    console.log(`EMAIL_HOST="smtp.ethereal.email"`);
    console.log(`EMAIL_USER="${testAccount.user}"`);
    console.log(`EMAIL_PASSWORD="${testAccount.pass}"`);
    console.log(`EMAIL_FROM="Streamify <noreply@streamify.com>"`);
    console.log(`FRONTEND_URL="http://localhost:5173"`);
    console.log(`NODE_ENV="development"`);
    console.log("=".repeat(60));

    // Update .env file
    const envPath = path.join(__dirname, ".env");
    let envContent = "";

    if (fs.existsSync(envPath)) {
      envContent = fs.readFileSync(envPath, "utf8");
    }

    // Update or add email configuration
    const emailConfig = `
# Email Configuration (Auto-generated by setup-email.js)
EMAIL_HOST="smtp.ethereal.email"
EMAIL_USER="${testAccount.user}"
EMAIL_PASSWORD="${testAccount.pass}"
EMAIL_FROM="Streamify <noreply@streamify.com>"
FRONTEND_URL="http://localhost:5173"
`;

    // Remove old email config if exists
    envContent = envContent.replace(/# Email Configuration[\s\S]*?FRONTEND_URL=".*"/g, "");

    // Add new email config
    envContent += emailConfig;

    fs.writeFileSync(envPath, envContent.trim() + "\n");

    console.log("\n✅ .env file updated automatically!");
    console.log("\n📝 Next Steps:");
    console.log("1. Restart your backend server: npm start");
    console.log("2. Sign up with any email");
    console.log("3. Check console for preview URL like:");
    console.log("   📮 Preview URL: https://ethereal.email/message/XXX");
    console.log("\n💡 Tip: These are TEST emails - they won't arrive in real inboxes");
    console.log("   You can view them at the preview URL shown in console\n");

    // Test the connection
    console.log("🔍 Testing email connection...");
    const transporter = nodemailer.createTransport({
      host: "smtp.ethereal.email",
      port: 587,
      secure: false,
      auth: {
        user: testAccount.user,
        pass: testAccount.pass,
      },
    });

    await transporter.verify();
    console.log("✅ Email connection test successful!\n");

  } catch (error) {
    console.error("❌ Error setting up email:", error.message);
    console.log("\n📝 Manual Setup Instructions:");
    console.log("1. Visit: https://ethereal.email/");
    console.log("2. Click 'Create Ethereal Account'");
    console.log("3. Copy credentials to your .env file");
  }
}

setupEtherealEmail();
